name: xapptor_auth
description: Authentication Module to develop fast and easy Login, Register, Restore Password, and Edit Account Screens. Using Firebase Auth and Firestore.
# repository: https://github.com/Xapptor/xapptor_auth
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.3

environment:
  sdk: '>=3.1.0 <5.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  firebase_storage: ^12.2.0

  sign_in_button: ^3.2.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0

  universal_platform: ^1.1.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  http: ^1.2.0
  crypto: ^3.0.3
  google_mlkit_face_detection: ^0.11.0
  camera: ^0.11.0
  font_awesome_flutter: ^10.7.0
  pointer_interceptor: ^0.10.1+1

  # xapptor_api_key:
  #   path: ../xapptor_api_key
  # xapptor_logic: ^0.0.3
  # xapptor_router: ^0.0.2
  # xapptor_translation: ^0.0.3
  # xapptor_ui: ^0.0.3

  xapptor_api_key:
    path: ../xapptor_api_key
  xapptor_logic:
    path: ../xapptor_logic
  xapptor_router:
    path: ../xapptor_router
  xapptor_translation:
    path: ../xapptor_translation
  xapptor_ui:
    path: ../xapptor_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/face_demos/
    - assets/images/face_demos/africa/
    - assets/images/face_demos/asia/
    - assets/images/face_demos/europe/
    - assets/images/face_demos/latin_america/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
